code --install-extension 13xforever.language-x86-64-assembly
code --install-extension coenraads.bracket-pair-colorizer
code --install-extension dunstontc.viml
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension gerane.Theme-Dark-Dracula
code --install-extension goessner.mdmath
code --install-extension james-yu.latex-workshop
code --install-extension justusadam.language-haskell
code --install-extension ms-python.python
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.go
code --install-extension ms-vscode.wordcount 
code --install-extension PKief.material-icon-theme
code --install-extension rebornix.prolog
code --install-extension ritwickdey.liveserver
code --install-extension sjhuangx.vscode-scheme
code --install-extension vscjava.vscode-java-debug
